### ISSUE TITLE
Moving build/serve scripts as rollup plugins

### ISSUE THREAD

**Issue by jholt1** [centrica-engineering/muon#409]
## Outcome

Building of tokens, creating of files to destination directory (dist), creation of custom element json and other assets (css) needs to be done as part of rollup. Removing the complexity within the scripts we currently have.

This means that scripts like `muon-build-styles` will not be needed to put in front of a serve or build.
`muon-serve` and `muon-build-storybook` will be wrapper scripts for calling rollup (muon-build-storybook is almost this anyway)

## Scope

- [x] Clean-up of destination (removing and creating).  (additional piece to make this skippable in case another script is doing it i.e. part of another framework)
- [x] #415
- [x] Creating analyzer json (#388)
- [x] Works for build, serve and storybook
- [x] Remove old scripts that are no longer needed (or offer them as standalone pieces)

**Comment by MekalaNagarajan-Centrica** [comment]
Test scripts PR #434

**Comment by PraveenAsokan** [comment]
I've run the automated tests for the components and ember app in the main branch. It's working fine. Hence closed.
