### ISSUE TITLE
[ns-inputter] update html template for accessibility

### ISSUE THREAD

**Issue by PtitBen** [centrica-engineering/muon#605]
## Outcome

We regain some of the aria attributes that made the inputter accessible, and that got lost when re-coding components with muon. 

## Scope

- [x] `aria-describedby` linked to the helper
- [x] update validation message HTTML template so that it brings the error message to screen readers.

We had these features in v2.9.8 of Nucleus. Here is a playground and some screenshots to compare the differences.

## Playground

https://playground.nucleus.design/#project=715e4417-8c1e-4d4a-84bc-2468a9feba4f

### Nucleus - live

![nucleus-live](https://github.com/user-attachments/assets/d2a98bb0-0e9a-47cd-a1a8-0f11fcdf4a04)

### Nucleus - v2.9.8

![nucleus-v2 9 8](https://github.com/user-attachments/assets/fd6a176d-accc-4330-807d-6a46603b2863)

**Comment by MekalaNagarajan-Centrica** [comment]
- PR to fix the inputter accessibility https://github.com/centrica-engineering/muon/pull/606
  - Helper `aria-describedby`
  - Validation message `role="alert"` & `aria-live="assertive"`

**Comment by MekalaNagarajan-Centrica** [comment]
- Playground link for inputter with helper / tip-details in live, 2.9.x and latest fix https://playground.nucleus.design/#project=e83df4da-6aed-4b08-b9af-b03f907cb18c

**Comment by PraveenAsokan** [comment]
Released in Nucleus v3.15.3
